### ISSUE TITLE
startfile in a subfolder

### ISSUE THREAD

**Issue by eirikb** [nodester/nodester#117]
First problem is nodester app init:

```
$ nodester app create eirikb-test server/server.js
$ nodester app init eirikb-test
...
nodester info writing app files
fs.js:221
    return binding.open(path, stringToFlags(flags), mode);
Error: EBADF, Bad file descriptor 'eirikb-test/server/server.js'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:522:15)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:234:20
    at ChildProcess.exithandler (child_process.js:100:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)
```

Then I manually created subfolder server and added two files, server.js and calc.js
server/server.js:

```
var http = require('http'),
    calc = require('./calc');

http.createServer(function(req, res) {
    res.writeHead(200, {
        'Content-Type': 'text/plain'
    });
    res.end('calc(4,5): ' + calc.add(4, 5));
}).listen(9667);
```

server/calc.js:

```
exports.add = function(a, b) {
    return a + b;
};
```

The output from nodester logs looks like this:

```
$ nodester logs
nodester info Showing logs for: eirikb-test
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (19138) at  Wed, 27 Apr 2011 20:52:20 GMT
Error: Cannot find module '/calc'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at Function.require (module.js:348:19)
    at /node/nodester/scripts/launch_chrooted_app.js:159:26
    at server/server.js:2:12
    at /node/nodester/scripts/launch_chrooted_app.js:205:20
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:864:12){ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'/calc\'' }
```

Note:
using require('./server/calc') in server.js works.
So I have been using this hack so far:

```
path = require('path'),
dir = path.join('/', path.join(path.dirname(__filename), '/')),
calc = requrie(dir + 'calc');
```

Although this should not be necessary.

**Comment by eirikb** [comment]
I tried moving server.js to root and add algo.js in server-folder.
So:

```
$ ls -lR
 .:
 total 8
 drwxr-xr-x 2 eirikb eirikb 4096 Apr 27 23:19 server
 -rw-r--r-- 1 eirikb eirikb  215 Apr 27 23:18 server.js
 ./server:
 total 8
 -rw-r--r-- 1 eirikb eirikb 50 Apr 27 23:19 algo.js
 -rw-r--r-- 1 eirikb eirikb 90 Apr 27 23:21 calc.js
```

With this content:

```
 $ cat server/calc.js 
 var algo = require('./algo');

 exports.add = function(a, b) {
      return algo.add(a, b);
 };

 $ cat server/algo.js 
 exports.add = function(a, b) {
      return a + b;
 };
```

In server.js I do require('./server/calc'); but beside that this actually works. So the problem is putting server.js in server-folder.

**Comment by eirikb** [comment]
Using node_modules:
I kept server.js on root, then moved calc.js and algo.js from ./server/ to ./node_modules/.
This seems to works very well, now I can do require('calc') in server.js and requrie('algo') in calc.js

**Comment by chrismatthieu** [comment]
davglass: I don't know how you have your files setup, but this works: http://davglass.nodester.com/
[1:30pm] eirikb: And that has a subfolder with the server.js in it?
[1:30pm] eirikb: Because if I have ./server.js and ./players.js that will work fine. But ./subfolder/server.js and ./subfolder/players.js does not
[1:31pm] davglass: https://gist.github.com/867559
davglass: That is the example I test against.

**Comment by DanBUK** [comment]
Issues with relative path'ing are resolved once #143 is tested.

**Comment by troygoode** [comment]
This issue is still present. The root of my repo has a "src" directory which contains all the node code. I configured the app start file to be "./src/app.js" but now none of my local module requires work. Example:

In my src/app.js locally I'm able to require "config.js" like so:

```
require('./config');
```

This works when starting the app from my repository root ("node src/app.js") but does not work from nodester. For nodester to work I have to execute:

```
require('./src/config');
```

despite the fact that app.js itself is in ./src. Changing my require paths to work with nodester then causes my local "node src/app.js" to not work.

This is a bummer.

**Comment by DanBUK** [comment]
Sorry Troy, I did say -once- #143 is resolved, which is currently in testing.

**Comment by troygoode** [comment]
yup, saw that but since there hasn't been any updates in a few weeks I thought I'd give the issue a little bit of a bump :-)
