### ISSUE TITLE
gitreset missing from docs page (http://nodester.com/api.html)

### ISSUE THREAD

**Issue by JasonWoof** [nodester/nodester#127]
Please add a section to http://nodester.com/api.html describing how to do the gitreset command with curl.

Thanks,   - Jason

**Comment by JasonWoof** [comment]
This seems to work:

```
curl -u user:pass -X DELETE http://api.nodester.com/gitreset -d "appname=foo"
```

**Comment by yocontra** [comment]
Fixed now, closing.

**Comment by JasonWoof** [comment]
I still don't see it at http://nodester.com/api.html

I hope that is only because that's running an older version of the code.

**Comment by chrismatthieu** [comment]
Ah, gitreset is in the CLI list but not the API list.  Good catch!  We will be releasing a new website shortly and will make that update there.  Thanks!

**Comment by JasonWoof** [comment]
lovely, thank you :)
