### ISSUE TITLE
npm install broken?

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester#219]
```
 $ nodester create npm-express-test
 ...
 $ nodester app init npm-express-test
 ...
 $ cd npm-express-test
 ...
 $ nodester npm install express
 nodester info installing to app: npm-express-test
 nodester info installing these npm packages: express
 nodester /bin/sh: line 0: cd: /node/app/martypdx/3888-cd6209234100eca5f9a8a07b5a
 d16104_rw: No such file or directory
 nodester npm ERR! Could not create /node_modules/___express.npm
 nodester npm ERR! error installing express@2.4.6 Error: EACCES, Permission denie
 d '/node_modules/___express.npm'
 nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___express.npm
 '
 nodester npm ERR!
 nodester npm ERR! Please use 'sudo' or log in as root to run this command.
 nodester npm ERR!
 nodester npm ERR!     sudo npm "install" "express"
 nodester npm ERR!
 nodester npm ERR! or set the 'unsafe-perm' config var to true.
 nodester npm ERR!
 nodester npm ERR!     npm config set unsafe-perm true
 nodester npm ERR!
 nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
 nodester npm ERR! command "node" "/usr/bin/npm" "install" "express"
 nodester npm ERR! cwd /
 nodester npm ERR! node -v v0.4.9
 nodester npm ERR! npm -v 1.0.18
 nodester The following files couldn't be removed.
 nodester Remove them manually and try again
 nodester sudo rm -rf "/node_modules/.bin/express" "/node_modules/express/lib/uti
 ls.js" "/node_modules/express/lib" "/node_modules/express" "/node_modules/.bin/e
 xpress" "/node_modules/express/lib/utils.js" "/node_modules/express/lib" "/node_
 modules/express"
 nodester npm ERR!
 nodester npm ERR! Additional logging details can be found in:
 nodester npm ERR!     /npm-debug.log
 nodester npm not ok

 nodester warn you should restart your app after you are finished installing pack
 ages.
```

This fails. Also, just doing this after app init before any npm install  shows a broken express install:

```
 $ nodester npm list
 nodester info list npm packages for app: npm-express-test
 nodester ├── crypto@0.0.1
 nodester ├─┬ express@2.4.3
 nodester │ ├── connect@1.6.0
 nodester │ ├── mime@1.2.2
 nodester │ └── qs@0.3.0
 nodester ├── imageable@0.3.4
 nodester └── jade@0.13.0
 nodester /bin/sh: line 0: cd: /node/app/martypdx/3888-cd6209234100eca5f9a8a07b5a
 d16104_rw: No such file or directory
 nodester The following files couldn't be removed.
 nodester Remove them manually and try again
 nodester sudo rm -rf "npm-debug.log"
```

**Comment by JasonOffutt** [comment]
I'm experiencing something similar. I'm wondering if it has something to do with not running `nodester app init [appname]`. I've been doing a little testing and it seems to only happen when I try to install npm modules against one of my existing Node apps that I just created in Nodester.

Here are the steps I'm taking to reproduce the problem:

```
nodester app create foobar
...
nodester info foobar  #optional, I've tried skipping the git push and installing against an empty repo and gotten the same result
...
git remote add url  #optional
...
git push nodester master  #optional
...
nodester npm install foobar express
nodester info installing to app: jordanrift
nodester info installing these npm packages: express
nodester /bin/sh: line 0: cd: /node/app/JasonOffutt/4002-daddb4278589ec31230caff2fbdb6e49_rw: No such file or directory
nodester npm ERR! error installing express@2.4.6 Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! error rolling back express@2.4.6 Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.30
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.30
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
... # The error message goes on and on...
```

The interesting thing is that when I have Nodester create the hello world app for me, the npm install goes fine.

```
nodester app create foobarbaz
...
nodestar app init foobarbaz
...
nodester npm install foobarbaz express
... # great success!
```

**Comment by yocontra** [comment]
As of now the write permissions are done after an init or git push. A workaround is to init/push first before trying to install npm packages. I'll put this on my TODO list

**Comment by JasonOffutt** [comment]
I just tried doing a push before installing a package and still no dice. The app I've been testing with is named 'jordanrift'. It's using a number of packages (express, jade, jasmine-node, nodemailer, connect, underscore, backbone and json2). The result I'm getting now is different from before, although it still fails citing permission/authentication issues.

``` shell
git push nodester master
... # so far so good
nodester npm install express
nodester info grabbing dependencies from package.json...
nodester info installing to app: express
nodester info installing these npm packages: express,jade,jasmine-node,nodemailer,connect,underscore,backbone,json2
nodester info { response: '{"status" : "failure - authentication for express failed."}\n',
  errorCode: 400 }
nodester ERROR [HTTP 400] failure - authentication for express failed.
```

So for now, in my situation, the only way to get my app running in Nodester appears to be initing first, then push. Pushing alone doesn't seem to be setting up my permissions.

**Comment by yocontra** [comment]
Upgrade to the latest CLI/API, it gives more verbose logging.

**Comment by JasonOffutt** [comment]
Done. I'm on version 0.2.34. The error output on my end doesn't seem to change.

``` shell
[JasonO ~/dev/projects/jordan_rift]$ nodester npm install express
nodester info grabbing dependencies from package.json...
nodester info installing to app: express
nodester info installing these npm packages: express,jade,jasmine-node,nodemailer,connect,underscore,backbone,json2
nodester info { response: '{"status" : "failure - authentication for express failed."}\n',
  errorCode: 400 }
nodester ERROR Fatal Error! API Response: {"status" : "failure - authentication for express failed."}

Reason: HTTP Error 400 returned.
[JasonO ~/dev/projects/jordan_rift]$ nodester -v
0.2.34
[JasonO ~/dev/projects/jordan_rift]$ 
```

**Comment by yocontra** [comment]
Hmm this might just be an issue with the CLI. I see a bug with the package.json install from your log output. Looking into it now

**Comment by yocontra** [comment]
Can you confirm that this is still an issue? We changed a lot concerning permissions

**Comment by JasonOffutt** [comment]
Yep. I'm still getting this issue. To confirm, I'm running the Nodester CLI version 0.2.34 (this appears to be the lastest version on NPM).

I created a fresh app to test it against too. Here were the steps that I took from my existing Node app directory:
1. git remote rm nodester
2. nodester app create jasonoffutt
3. git remote add nodester URL_RETURNED_FROM_APP_CREATE
4. nodester app info jasonoffutt
5. git push nodester master
6. nodester npm install express

Here's a copy of my bash session...

``` shell
JasonO ~/dev/projects/jordan_rift]$ nodester app create jasonoffutt
nodester info creating app: jasonoffutt server.js
nodester info successfully created app jasonoffutt to will run on port 12959 from server.js
nodester info run nodester app init jasonoffutt to setup this app.
[JasonO ~/dev/projects/jordan_rift]$ nodester app info jasonoffutt
nodester info Gathering information about: jasonoffutt
nodester warn jasonoffutt on port 12959 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21.git
nodester info appfile: server.js
[JasonO ~/dev/projects/jordan_rift]$ git remote add nodester git@nodester.com:/node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21.git
[JasonO ~/dev/projects/jordan_rift]$ git push nodester master
Nodester!
Counting objects: 2496, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2185/2185), done.
Writing objects: 100% (2496/2496), 7.13 MiB | 1.14 MiB/s, done.
Total 2496 (delta 375), reused 0 (delta 0)
remote: Syncing repo with chroot
remote: From /node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21
remote:  * [new branch]      master     -> origin/master
remote: Attempting to restart your app: 4806-934336cf2f3f7a1caccfdd0cabe29e21
remote: {"status":"failed to restart"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21.git
 * [new branch]      master -> master
[JasonO ~/dev/projects/jordan_rift]$ 
[JasonO ~/dev/projects/jordan_rift]$ nodester npm install jasonoffutt express
nodester info installing to app: jasonoffutt
nodester info installing these npm packages: express
nodester /bin/sh: line 0: cd: /node/app/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! error installing express@2.5.2 Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! error rolling back express@2.5.2 Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/.bin/express'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/.bin/express
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
```

**Comment by yocontra** [comment]
Created a new app and followed the same process.

```

contra@ubuntu:~/Desktop/Projects/lolcontra$ nodester npm install express
The "sys" module is now called "util". It should have a similar interface.
nodester info installing to app: lolcontra
nodester info installing these npm packages: express
nodester ├── mkdirp@0.0.7
nodester ├── mime@1.2.4
nodester ├── qs@0.4.0
nodester └── connect@1.8.2
nodester 

nodester warn you should restart your app after you are finished installing packages.
contra@ubuntu:~/Desktop/Projects/lolcontra$ 
```

Try starting your app or running init before installing anything to it via npm. It probably hasn't set up your application folder

**Comment by JasonOffutt** [comment]
OK, first I tried starting it then running the install and I got the same error.

Next I executed init and was able to install after the init. The problem is that init seems to have removed all my code, when I run my app now, I get the default "hello world" behavior. My existing app doesn't appear to be running on Nodester at all.

If I try to push, I get the error below. Even after a `git push nodester master -f`, I'm still just getting 'Hello World'.

So it looks like init fixed this issue, but messed with my local git repo.

``` shell
[JasonO ~/dev/projects/jordan_rift]$ git push nodester master
Nodester!
To git@nodester.com:/node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@nodester.com:/node/git/JasonOffutt/4806-934336cf2f3f7a1caccfdd0cabe29e21.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
[JasonO ~/dev/projects/jordan_rift]$ 
```

Just to further note, that I think we confirmed before that 'init' seems to set everything up correctly, yet that doesn't seem to be part of the workflow for an existing Node app. Is there a way we can run init on the server only? Maybe just add a --remoteonly flag to the CLI or something similar?

The solution now seems to be to follow the "New App" workflow of create > init > copy over existing app code > push > install

**Comment by yocontra** [comment]
Ah, init overwrote your existing folder. `git pull origin master` before trying to push again. Check your garbage bin, your files might still be in there. AFAIK the CLI should have absolutely not done that because it warns me every time. Make sure you are in your app folder while trying to do anything

**Comment by JasonOffutt** [comment]
Luckily, it didn't delete anything, it just stuck the new code into a separate folder called 'jasonoffutt'. I think I'm good for now. I'll keep you guys posted if I run into anything else.

**Comment by yocontra** [comment]
Sorry for the inconvenience! Having the logic to setup your git repo in init is really stupid since that should be optional, looking into fixing that now.
