### ISSUE TITLE
Process died with exit code 127. Restarting...

### ISSUE THREAD

**Issue by albertosantini** [nodester/nodester#308]
The apps are offline and don't restart:

Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Error: Restarted too many times, bailing.

I tried with three apps and also the simplest app doesn't restart.

**Comment by chrismatthieu** [comment]
We fixed the /apps and /app PUT issues yesterday. We are working on an issue with starting and cloning apps today. Hopefully services will be restored shortly.

**Comment by JavascriptMick** [comment]
Still unable to start my app

New PID: 13137
chroot_runner
chroot_runner
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Error: Restarted too many times, bailing.

**Comment by chrismatthieu** [comment]
We are aware that this issue still exists. It's probably a simple problem to solve if we had a strong Linux system engineer member on the core team. I have researched this issue for several hours a day and have not been able to solve it. 

The API returns success but the app is not properly being started in the sandbox. The system is aware of the failure and tried to restart the app a few times and then gives up (by design).

**Comment by albertosantini** [comment]
@chrismatthieu After digging the nodester code, I report you a few thoughts.

Exit code 127 usually is due to a command not found or a possible problem with the path.

Recently I understood you updated nodester resources, I mean, disk resources.

In scripts/chroot_runner.js there is the spawn, in start_child method, of '/usr/bin/coffee' or '/usr/bin/node' executables.

I suppose you checked the existence and the **executable permissions** of that command (I would check also the permissions about the 'args' and the 'env').

My two cents.

**Comment by jtwebman** [comment]
I get this same error on http://googleplusrss.nodester.com but I am not using Coffee script. I am using express though so they might be using it.

**Comment by chrismatthieu** [comment]
THANKS TO @DAVGLASS NODESTER APPS ARE STARTING AGAIN!  PLEASE GIVE HIM A SHOUT OUT ON TWITTER!
