### ISSUE TITLE
Git pushes not updating app.

### ISSUE THREAD

**Issue by graemeworthy** [nodester/nodester#33]
A couple days ago git pushes stopped updating my app.
I created a new one to test that this was the case, and it also does not apply changes when I git push.
stoping and starting the app after pushing also does not trigger an update.

I have done some sleuthing and there is a clue.

The git push command response includes this line
remote: kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

which indicates that kill is not receiving a pid.

The .app.pid file is only written in one place /scripts/launch_chrooted_apps.js
And it was changed two days ago, roughly when pushes stopped being applied.

https://github.com/nodester/nodester/commit/0b39a10aa96eb237b29936427dc1404c13232e37

**Comment by chrismatthieu** [comment]
I seem to have a stuck instance:

Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 305 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: From /home/ec2-user/hosted_apps/davglass/239-4a17a8d4acc5c87900776490e9419aa2.git/.
remote:    f4a6ea9..67a4ef9  master     -> origin/master
remote: Updating f4a6ea9..67a4ef9
remote: Fast-forward
remote:  server.js |    2 ++
remote:  1 files changed, 2 insertions(+), 0 deletions(-)
remote: kill: usage: kill [-s sigspec | -n signum | -sigspec] pid |
jobspec ... or kill -l [sigspec]
To ec2-user@nodester.com:/home/ec2-user/hosted_apps/davglass/239-4a17a8d4acc5c87900776490e9419aa2.git
  f4a6ea9..67a4ef9  master -> master

I start/stop/restart the instance and it reports that it's running,
but it never refreshes..

## 

Dav Glass
davglass@gmail.com
blog.davglass.com

**Comment by DanBUK** [comment]
Ok, I've spent a couple of hours debugging this and I think i've got it sorted.

Will try and push updates to the repo later and then http://nodester.com and http://bejes.us .

**Comment by davglass** [comment]
Thanks Dan, I just created a new app and it's dead now too.

**Comment by DanBUK** [comment]
Have committed and deployed the code, but there is still a bug for the first start of an app. It works via the CLI/API for stop|start|restart. Will look again later on.

**Comment by graemeworthy** [comment]
Issue still stands, at least on nodester.com
I created an app via the cli, pushed my start file with git, and it worked.
Then I made a change to the start file, pushed it, and the change did not appear.
I restarted the app via the cli restart, and the change did not appear.

**Comment by DanBUK** [comment]
Based upon this error report, I think it's app restart that is failing (it's also used in a git push).

I will debug further.

**Comment by cschram** [comment]
I'm also having this issue on Nodester. Both CLI and CURL commands to stop/start/restart don't work.

**Comment by DanBUK** [comment]
Abjorn, what's your appname that's failing to start?

**Comment by cschram** [comment]
noctune

I was also talking to someone on #nodester that said all his apps have the same issue.

**Comment by davglass** [comment]
Dan, I noticed on my local install that sometimes one of the .app.pid's fails to write anything to it. Once that happens, I can't start/stop/restart the app at all. It's stuck in that state until you stop/start all apps again.

**Comment by dvbportal** [comment]
Same issue here. The log file shows the first version of the app. It is called tree. I guess, we need a recover API in case something goes wrong. It should search the app in the process list rather than using app.pid

**Comment by davglass** [comment]
In the app_stop of the API it only checks for the existence of the app.pid file. If that fails it does nothing, it should be able to exec this command to get the pid from the gitrepo id:

`ps aux | awk '/3-70067d78a9c51ab58d79209951ad6350/ && !/awk/ {print $2}'`

`ps aux | awk '/<gitrepo id>/ && !/awk/ {print $2}'`

Then call `process.kill` on it.

**Comment by davglass** [comment]
I added a fix here: davglass@d9c51cdeba2d9a2086369e2281d8eef4eaff48f3

And submitted a Pull Request here: #40

**Comment by dvbportal** [comment]
Dave, thanks for taking care of this. Great idea to use the repo ID.

**Comment by DanBUK** [comment]
Ok so these changes have been pushed to live. I've done some testing and have had apps successfully restarting. Please re-test at let us know if there are still problems.

**Comment by graemeworthy** [comment]
Still Broken.

The 'content' of the app does not update along with the gitrepo.

I have written a test of this using ruby, please add credentials and then run this file.

https://gist.github.com/819829

I makes a file called test.js, which is a server that echoes 'this is version: 0'
I then update the file to 'this is version: 1' and push to the git repo.

The app remains unchanged and still reports 'this is version: 0'

**Comment by DanBUK** [comment]
Graeme,

What is the repo path of your app that is failing?

Cheers,

DanB.

**Comment by DanBUK** [comment]
Graeme,

There was a bug that meant for apps where the PID file wasn't written properly it wouldn't get removed. And would therefore cause restarts to fail. I've modified this now.

Commit: f5145c17f039a01477ac70af20a3ac02da96b3fd

Cheers,

DanB.

**Comment by graemeworthy** [comment]
Still not working for some reason.

The repo that I'm using to test this is 'gwtest' 
http://gwtest.nodester.com

**Comment by chrismatthieu** [comment]
Could you try it again?  We believe that this issue has been resolved.  Let us know so that we can close this ticket if it is or continue working on it.

Thanks,
Chris

**Comment by JacksonTian** [comment]
When I restart the jackson.nodester.com,  It can be accessed now.

**Comment by dvbportal** [comment]
Hi Chris,

I still can't start or stop tree.nodester.com

$ nodester apps
nodester info tree on port 8520 running: failed-to-stop
- or -
  $ nodester app stop tree
  nodester info Checking config..
  nodester info Attemping to stop app: tree
  nodester ERRO false

It is not running though.

Logfile still shows output from 1st version. I tried everything: git push, nodester start, nodester stop. I guess we need more diagnostics, like why can't it stop, was the pid found?, was the process found?, error from OS?

**Comment by davglass** [comment]
dvbportal -- I'm not sure why it was dead, but I started it by hand just now..

**Comment by dvbportal** [comment]
..and it runs now. Thanks.

**Comment by davglass** [comment]
Closing based on my latest deployment..
